### PR TITLE
Basic design for home page.

### PR DESCRIPTION
**Pull request by WillTheDeveloper**
- Added text to home page.
- Created cool background for text.
- Created all the other pages you are going to need.
- Fixed links between each page.

### CODE REVIEW

**Review by peppy10003 — APPROVED** [review]
Ballin

**Comment by WillTheDeveloper** [comment]
@peppy10003 Delete that file and then do the merge. I copied it across anyway so you won't lost anything.

**Review by ghost — COMMENTED** [review]
Looks decent but you got your .idea settings folder in there rip >.<

**Review by ghost — APPROVED** [review]
Good code there may be a conflict though

**Review by ghost — APPROVED** [review]
👍 This is brilliant

**Pull request merged**
